- name: "install de package"
  apt:
   name: "{{ item }}"
   update_cache: yes
   state: present
  with_items:
    - python3-boto
    - python3-boto3
    - python3

- name: create key pair using key_material obtained using 'file' lookup plugin
  ec2_key:
    name: my_keypair
    key_material: "{{ lookup('file', '/etc/ansible/roles/AWS/tasks/mykey.pub') }}"

- ec2:
    key_name: my_keypair
    region: eu-west-1 
    instance_type: t2.micro
    instance_tags:
        Name: Ec2_create_via_ansible_to_destroy
        Date: 2022/02/18
    image: ami-0c7625fcaabee0286
    wait: yes
    group_id: sg-0033ea4c3901becbb
    count: 1
    vpc_subnet_id: subnet-5a1f1212
    assign_public_ip: yes
   
